import { MusicPlayerProvider } from '@/store/music-player-context';
import Header from '../(components)/header';
import MusicPlayer from '../(components)/music-player';
import { verifyAuth } from '@/lib/lucia';
import { redirect } from 'next/navigation';

export const metadata = {
  title: 'Tunehub',
  description: 'Generated by create next app',
};
const AuthLayout = async ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  const { user } = await verifyAuth();
  if (!user) {
    redirect('/');
  }
  return (
    <MusicPlayerProvider>
      <Header firstName={user.firstName} />
      <main className="flex-grow ">{children}</main>

      <MusicPlayer />
    </MusicPlayerProvider>
  );
};

export default AuthLayout;
